# This sample data was generated by ChatGPT, an AI language model by OpenAI.
# It is used to poplulate the database for testing purposes.

pilots = [
    (1, "John", "Smith", "L1001"),
    (2, "Alice", "Brown", "L1002"),
    (3, "David", "Wilson", "L1003"),
    (4, "Karen", "Jones", "L1004"),
    (5, "Michael", "Lee", "L1005"),
    (6, "Sophia", "Taylor", "L1006"),
    (7, "Chris", "Miller", "L1007"),
    (8, "Emma", "Davis", "L1008"),
    (9, "Robert", "Clark", "L1009"),
    (10, "Olivia", "Moore", "L1010")
]

destinations = [
    (1, "London", "UK", "LHR"),
    (2, "Paris", "France", "CDG"),
    (3, "New York", "USA", "JFK"),
    (4, "Dubai", "UAE", "DXB"),
    (5, "Tokyo", "Japan", "HND"),
    (6, "Toronto", "Canada", "YYZ"),
    (7, "Berlin", "Germany", "BER"),
    (8, "Rome", "Italy", "FCO"),
    (9, "Madrid", "Spain", "MAD"),
    (10, "Sydney", "Australia", "SYD")
]

aircrafts = [
    (1, "Delta Air Lines", "Boeing 737", 160),
    (2, "American Airlines", "Airbus A320", 150),
    (3, "British Airways", "Boeing 777", 300),
    (4, "Emirates", "Airbus A380", 500),
    (5, "JetBlue", "Embraer E190", 100),
    (6, "Lufthansa", "Bombardier CRJ900", 90),
    (7, "Qantas", "Boeing 747", 400),
    (8, "Singapore Airlines", "Airbus A350", 350),
    (9, "Delta Air Lines", "McDonnell Douglas MD-88", 155),
    (10, "Air New Zealand", "ATR 72", 70)
]

flights = [
    (1, 1, 2, 1, "2025-06-23 08:00:00", "2025-06-23 10:00:00"),   # John Smith flying to Paris with Boeing 737
    (2, 2, 3, 2, "2025-06-14 09:30:00", "2025-06-14 13:00:00"),   # Alice Brown flying to New York with Airbus A320
    (3, 3, 4, 3, "2025-06-25 14:00:00", "2025-06-25 22:00:00"),   # David Wilson flying to Dubai with Boeing 777
    (4, 4, 5, 4, "2025-06-12 07:00:00", "2025-06-12 19:00:00"),   # Karen Jones flying to Tokyo with Airbus A380
    (5, 5, 6, 5, "2025-06-20 12:00:00", "2025-06-20 16:00:00"),   # Michael Lee flying to Toronto with Embraer E190
    (6, 6, 7, 6, "2025-06-18 11:00:00", "2025-06-18 13:30:00"),   # Sophia Taylor flying to Berlin with Bombardier CRJ900
    (7, 7, 8, 7, "2025-06-11 15:00:00", "2025-06-11 17:00:00"),   # Chris Miller flying to Rome with Boeing 747
    (8, 8, 9, 8, "2025-06-24 10:00:00", "2025-06-24 12:30:00"),   # Emma Davis flying to Madrid with Airbus A350
    (9, 9, 10, 9, "2025-06-13 20:00:00", "2025-06-14 06:00:00"),  # Robert Clark flying to Sydney with McDonnell Douglas MD-88
    (10, 10, 1, 10, "2025-06-19 06:00:00", "2025-06-19 14:00:00"), # Olivia Moore flying to London with ATR 72
    (11, 1, 3, 1, "2025-06-22 08:00:00", "2025-06-22 16:00:00"),   # John Smith flying to New York with Boeing 737 
    (12, 2, 2, 2, "2025-06-17 09:00:00", "2025-06-17 11:00:00"),   # Alice Brown flying to Paris with Airbus A320 
    (13, 3, 2, 3, "2025-06-21 10:00:00", "2025-06-21 12:00:00"),   # David Wilson flying to Paris with Boeing 777 
    (14, 4, 5, 1, "2025-06-16 07:00:00", "2025-06-16 19:00:00"),   # Karen Jones flying to Tokyo with Boeing 737 
    (15, 5, 6, 2, "2025-06-15 12:00:00", "2025-06-15 16:00:00")    # Michael Lee flying to Toronto with Airbus A320
]

