# This sample data was generated by ChatGPT, an AI language model by OpenAI.
# It is used to poplulate the database for testing purposes.

pilots = [
    (1, "John", "Smith", "L1001"),
    (2, "Alice", "Brown", "L1002"),
    (3, "David", "Wilson", "L1003"),
    (4, "Karen", "Jones", "L1004"),
    (5, "Michael", "Lee", "L1005"),
    (6, "Sophia", "Taylor", "L1006"),
    (7, "Chris", "Miller", "L1007"),
    (8, "Emma", "Davis", "L1008"),
    (9, "Robert", "Clark", "L1009"),
    (10, "Olivia", "Moore", "L1010")
]

destinations = [
    (1, "London", "UK", "LHR"),
    (2, "Paris", "France", "CDG"),
    (3, "New York", "USA", "JFK"),
    (4, "Dubai", "UAE", "DXB"),
    (5, "Tokyo", "Japan", "HND"),
    (6, "Toronto", "Canada", "YYZ"),
    (7, "Berlin", "Germany", "BER"),
    (8, "Rome", "Italy", "FCO"),
    (9, "Madrid", "Spain", "MAD"),
    (10, "Sydney", "Australia", "SYD")
]

aircrafts = [
    (1, "Boeing 737", "Delta Air Lines", 160),
    (2, "Airbus A320", "American Airlines", 150),
    (3, "Boeing 777", "British Airways", 300),
    (4, "Airbus A380", "Emirates", 500),
    (5, "Embraer E190", "JetBlue", 100),
    (6, "Bombardier CRJ900", "Lufthansa", 90),
    (7, "Boeing 747", "Qantas", 400),
    (8, "Airbus A350", "Singapore Airlines", 350),
    (9, "McDonnell Douglas MD-88", "Delta Air Lines", 155),
    (10, "ATR 72", "Air New Zealand", 70)
]

flights = [
    (1, 1, 1, 2, "Manchester", "2025-06-08 09:00", "2025-06-08 11:30"),
    (2, 2, 2, 3, "London", "2025-06-08 14:00", "2025-06-08 17:00"),
    (3, 3, 3, 4, "Paris", "2025-06-09 07:00", "2025-06-09 15:00"),
    (4, 4, 4, 5, "Berlin", "2025-06-10 12:00", "2025-06-10 23:00"),
    (5, 5, 5, 6, "Rome", "2025-06-11 06:00", "2025-06-11 12:00"),
    (6, 6, 6, 1, "New York", "2025-06-12 20:00", "2025-06-13 08:00"),
    (7, 7, 7, 8, "Madrid", "2025-06-13 10:30", "2025-06-13 14:30"),
    (8, 8, 8, 9, "Tokyo", "2025-06-14 16:00", "2025-06-15 01:00"),
    (9, 9, 9, 10, "Toronto", "2025-06-15 07:00", "2025-06-16 00:00"),
    (10, 10, 10, 1, "Sydney", "2025-06-16 06:00", "2025-06-16 18:00")
]

