# This sample data was generated by ChatGPT, an AI language model by OpenAI.
# It is used to poplulate the database for testing purposes.

pilots = [
    (1, "John", "Smith", "L1001"),
    (2, "Alice", "Brown", "L1002"),
    (3, "David", "Wilson", "L1003"),
    (4, "Karen", "Jones", "L1004"),
    (5, "Michael", "Lee", "L1005"),
    (6, "Sophia", "Taylor", "L1006"),
    (7, "Chris", "Miller", "L1007"),
    (8, "Emma", "Davis", "L1008"),
    (9, "Robert", "Clark", "L1009"),
    (10, "Olivia", "Moore", "L1010")
]

destinations = [
    (1, "London", "UK", "LHR"),
    (2, "Paris", "France", "CDG"),
    (3, "New York", "USA", "JFK"),
    (4, "Dubai", "UAE", "DXB"),
    (5, "Tokyo", "Japan", "HND"),
    (6, "Toronto", "Canada", "YYZ"),
    (7, "Berlin", "Germany", "BER"),
    (8, "Rome", "Italy", "FCO"),
    (9, "Madrid", "Spain", "MAD"),
    (10, "Sydney", "Australia", "SYD")
]

aircrafts = [
    (1, "Boeing 737", "Delta Air Lines", 160),
    (2, "Airbus A320", "American Airlines", 150),
    (3, "Boeing 777", "British Airways", 300),
    (4, "Airbus A380", "Emirates", 500),
    (5, "Embraer E190", "JetBlue", 100),
    (6, "Bombardier CRJ900", "Lufthansa", 90),
    (7, "Boeing 747", "Qantas", 400),
    (8, "Airbus A350", "Singapore Airlines", 350),
    (9, "McDonnell Douglas MD-88", "Delta Air Lines", 155),
    (10, "ATR 72", "Air New Zealand", 70)
]

flights = [
    (1, 1, 2, 1, "2025-06-11 08:00:00", "2025-06-11 10:00:00"),   # John Smith flying to Paris with Boeing 737
    (2, 2, 3, 2, "2025-06-12 09:30:00", "2025-06-12 13:00:00"),   # Alice Brown flying to New York with Airbus A320
    (3, 3, 4, 3, "2025-06-13 14:00:00", "2025-06-13 22:00:00"),   # David Wilson flying to Dubai with Boeing 777
    (4, 4, 5, 4, "2025-06-14 07:00:00", "2025-06-14 19:00:00"),   # Karen Jones flying to Tokyo with Airbus A380
    (5, 5, 6, 5, "2025-06-15 12:00:00", "2025-06-15 16:00:00"),   # Michael Lee flying to Toronto with Embraer E190
    (6, 6, 7, 6, "2025-06-16 11:00:00", "2025-06-16 13:30:00"),   # Sophia Taylor flying to Berlin with Bombardier CRJ900
    (7, 7, 8, 7, "2025-06-17 15:00:00", "2025-06-17 17:00:00"),   # Chris Miller flying to Rome with Boeing 747
    (8, 8, 9, 8, "2025-06-18 10:00:00", "2025-06-18 12:30:00"),   # Emma Davis flying to Madrid with Airbus A350
    (9, 9, 10, 9, "2025-06-19 20:00:00", "2025-06-20 06:00:00"),  # Robert Clark flying to Sydney with McDonnell Douglas MD-88
    (10, 10, 1, 10, "2025-06-20 06:00:00", "2025-06-20 14:00:00"), # Olivia Moore flying to London with ATR 72
    (11, 1, 3, 1, "2025-06-21 08:00:00", "2025-06-21 16:00:00"),   # John Smith flying to New York with Boeing 737 
    (12, 2, 2, 2, "2025-06-22 09:00:00", "2025-06-22 11:00:00"),   # Alice Brown flying to Paris with Airbus A320 
    (13, 3, 2, 3, "2025-06-23 10:00:00", "2025-06-23 12:00:00"),   # David Wilson flying to Paris with Boeing 777 
    (14, 4, 5, 1, "2025-06-24 07:00:00", "2025-06-24 19:00:00"),   # Karen Jones flying to Tokyo with Boeing 737 
    (15, 5, 6, 2, "2025-06-25 12:00:00", "2025-06-25 16:00:00")    # Michael Lee flying to Toronto with Airbus A320
]

